---
# tasks file for nginx
- name: Load vaulted variables
  ansible.builtin.include_vars:
    file: vault.yml

- name: Install nginx package
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Deploy nginx configuration from template
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Deploy custom index.html page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Ensure nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes