---
# tasks file for nginx
- name: Ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false # To nie jest zmiana konfiguracyjna

- name: Install nginx package
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Ensure nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes