---
- name: Configure full server stack
  hosts: all
  roles:
    - role: common_tools
      tags:
        - tools
        - packages

    - role: firewall
      tags:
        - firewall
        - security

    - role: nginx
      tags:
        - nginx
        - web